spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.167.130:3306/moxibustion_zhsj?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: yjy
    password: s153g@ALIYUN
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
    type: com.zaxxer.hikari.util.DriverDataSource
mybatis:
  type-aliases-package: com.yjy.moxibustion.pojo
  mapper-locations: classpath:mapper/*.xml
server:
  port: 80
logging:
  level:
    com.yjy.momoxibustion-zhsj.dao.*: debug
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
### QQ
qqAppId: 101957228
qqAppSecret: 105d1b3d7d3610e8f4e04472578d85ec
qqRedirectUrl: http://www.s153g.cn/qq